config/routes.rb
# TODO - change accessibility via status and user_id.
# TODO Error handling, for EVERYTHING (phone number, etc)
# TODO - get avalara to work
# TODO - tip calculator - built in to say the percentage - AJAX ?? - DO NOT WANT TO HAVE TO REFReSH.
# TODO - talk to someone about the routes - especially the AJAX routes.


Rails.application.routes.draw do
  root 'mains#index'

  get "/information/", to: "mains#information", as: "information" 

  # OmniAuth
  get "/auth/:provider/callback" => "sessions#create"

  get "/sessions/login_failure", to: "sessions#login_failure", as: "login_failure"
  get "/sessions", to: "sessions#index", as: "sessions"
  delete "/sessions", to: "sessions#destroy"

  # RECEIPT
  resources :receipts, only: [:index, :new, :show, :create, :destroy] do
    # ListItems
    resources :list_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :guests, only: [:index, :new, :create, :show, :update] do

      resources :guest_items, only: [:index]
    end
  end

  get "receipts/:receipt_id/finalize", to: "receipts#finalize", as: "finalize_receipt"

  # TO HANDLE AJAX of creating new guest
  post "receipts/:receipt_id/guests/", to: "guest_items#create_guest", as: "AJAX_create_guest"

  post "/guests/:guest_id/guest_items/", to: "guest_items#update", as: "update_guest_items"

  # Page where user can select the tip and view the total for their order
  get "guests/:guest_id/tip", to: "guests#tip", as: "guests_tip"
  post "guests/:guest_id ", to: "guests#add_tip", as: "guests_tip_add"


  # get "/receipts/guests/:id/split", to: "guests#split", as: "split_receipt"
  # post "/receipts/guests/:id/", to: "guest_items#create", as: "post_guest_items"
end

app/models/guest_item.rb
class GuestItem < ApplicationRecord
  belongs_to :list_item
end

app/controllers/guest_items_controller.rb
class GuestItemsController < ApplicationController
  def create
    puts ">>>>>>>>> BEING CREATED GUEST ITEM!!!!!!!!!!"
    @new_guest_item = GuestItem.new(guest_item_params)
    if @new_guest_item.save
      redirect_to receipts_path
    else
      redirect_to root_path
    end
  end

  def index
    # Only need to display the items which are unclaimed OR Belong to the guest already
    @guest_id = params[:guest_id]

    @receipt_id = params[:receipt_id]

    # This is only called the first time you go to guest_items#index because the status changes within the method change_to_splittable. Bug occured because no longer going through the guest#new page.

    @receipt = Receipt.find(@receipt_id)
    if @receipt.status < 2
      # Calls method to generate the guest methods and to change the status.
      @receipt.change_to_splittable()
    end

    # DEBUGGING - guestItems are not appearing - are they being generated? - GuestItems are generated when you click "Let's begin splitting"

    @guest_items = GuestItem.includes(:list_item).where(list_items: {receipt_id: @receipt_id})

    @current_guest = Guest.find(params[:guest_id])

    # TODO - make the list of guests displayed to NOT include the current_guest
    @receipt_guests = Guest.where(receipt_id: @receipt_id)

    # FOR THE AJAX OF ADDING A NEW USER
    @new_guest = Guest.new

    # Do all items have a guest? If so then you should be able to finalize the receipt

  end

  def update
    # Id's that were checked come in an array of strings. Go through the array and update all the receipt items with the given guest's id. Additionally, needs to add the price of the item to the guests total.
    guest = Guest.find(params[:guest_id])
    # the item_total is 0 whenever this starts or else when the button is ever pressed more than once for an item it goes to that person.
    guest.item_total = 0

    # Additionally, all items with the guest_id of the person who submits, should be nil just in case they unchecked anything. Therefore, iterate through a list of guest_items with that guest_id and nil them out. Then the will get checked off again.

    @guest_items = GuestItem.where(guest_id: params[:guest_id])
    @guest_items.each do |item|
      item.guest_id = nil
      item.save
    end

    # Will get an error if nil, so this acts as a barrier for that.
    if params[:item_ids] != nil
      # May only select uclaimed items. Needs to be checked before submitting the rest.
      params[:item_ids].each do |id|
        check = GuestItem.find(id.to_i)
        if check.guest_id != nil
          # redirect_to receipt_guest_guest_items_path(receipt_id: params[receipt_id])
          flash[:error] = "NOTICE: You may only claim items not already claimed, to delete an item, pick a user and resubmit their order"
          receipt = Receipt.find(guest.receipt_id)

          puts "receipt_id: >>>>>>>>" + params[:receipt_id].to_s
          redirect_to receipt_guest_guest_items_path(receipt_id: receipt.id, guest_id: params[:guest_id])
          return
        end
      end



      # Iterating through the guest_items that were checked off. They are sent view an array as strings
      params[:item_ids].each do |id|

        # setting the guest_id on those items.
        update = GuestItem.find(id.to_i)
        update.guest_id = params[:guest_id]
        update.save
        # Adding the total of those items to the guest total.

        guest.item_total = guest.item_total + ListItem.find(update.list_item_id).price
        guest.save
      end
    end



    puts ">>>>>>" + params.to_s
    # redirect_to root_path
    redirect_to receipt_guest_path(receipt_id: Guest.find(params[:guest_id]).receipt_id, id: params[:guest_id])
  end

  def create_guest
    @new_guest = Guest.new(params[:guest])

    respond_to do |format|
      if @new_guest.save
        format.html {redirect_to @new_guest, notice: "Guest was successfully created"}
        format.js
        format.json{ render json: @new_guest, status: :created, location: @new_guest}
      else
        format.html { render action: "new" }
        format.json { render json: @new_guest.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def guest_item_params
    params.require(:guest_item).permit(:price, :receipt_id)
  end
end

app/helpers/guest_items_helper.rb
module GuestItemsHelper
end

app/views/guest_items/index.html.erb
<section>

  <h3 class="labels">Now, lets begin splitting</h3>

  <% if !flash[:error].blank? %>
    <div class="alert alert-info"><%= flash[:error] %></div>
  <% end %>

  <% if flash[:notice] %>
    <div class="notice text important"><h3><%= flash[:notice] %><h3></div>
  <% end %>

  <div class="">
    <h2 class="labels to-pop important">Current User: <%= @current_guest.name %></h2>
  <div>

  <p class="labels">To change the user, simply click on their name below or add a new guest if not in the list below. Unclaimed items are marked in yellow. Once all items are claimed, the receipt will be completely white. All items must be claimed before finalizing the receipt.ra</p>

  <% @receipt_guests.each do |guest| %>
    <p><%= link_to guest.name, receipt_guest_guest_items_path(receipt_id: guest.receipt_id, guest_id: guest.id), class:"labels"%></p>
  <% end %>

  <!-- Button trigger modal -->
  <button class="btn btn-primary" data-toggle="modal" data-target="#receipt-guest-<%= @receipt_id %>-notes">
    Add New Guest
  </button>

  <!-- Modal -->
  <div class="modal fade" id="receipt-guest-<%= @receipt_id %>-notes" tabindex="-1" role="dialog" aria-labelledby="receipt-guest-<%= @receipt_id %>-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title labels" id="receipt-guest-<%= @receipt_id %>-label">Add Guest</h4>
        </div>
        <div class="modal-body">
          <%= form_for @new_guest, :url => { method: :post, action: :create_guest, class:"form-horizontal", remote: true } do |f|%>

            <div class="form-group">
              <%= f.label :name, class: "col-md-4 control-label labels"   %>
              <%= f.text_field :name, class: "form-control"   %>
            </div>

            <div class="form-group">
              <%= f.label :phone, class: "col-md-4 control-label labels"   %>
              <%= f.text_field :phone, class: "form-control"   %>
            </div>

            <%= f.hidden_field :receipt_id, :value => params[:receipt_id] %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>


  <%= form_tag (update_guest_items_path(guest_id: @guest_id)), :class => 'remove-guest-number' do %>
    <table class="table-responsive">
      <tr class="receipt important">
        <th>Description</th>
        <th class="moneyright">Price</th>
        <th class="moneyright">Check</th>
      </tr>
      <% @guest_items.each do |item| %>
        <tr class="receipt <%= 'alert alert-warning' if item.guest_id == nil %>">
          <td><p><%= ListItem.find(item.list_item_id).description%></p></td>
          <td class="moneyright"><%= money_format(item.price)%></td>

          <!-- The checkbox should be prechecked it the guest_id id == guest.id -->

          <% if item.guest_id != @current_guest.id %>
            <td  class="center"><%= check_box_tag 'item_ids[]', item.id %></td>
            <%= h item.guest_id -%>
          <% else %>
            <td  class="center"><%= check_box_tag 'item_ids[]', item.id, true %></td>
            <%= h item.guest_id -%>
          <% end %>

          <!-- TODO maybe make what is visible to the guest different depending on what is available to be checked off -->

        </tr>
      <% end %>
    </table>

    <div class="actions">
      <input type="submit" value="Submit My Orders" class= "btn btn-primary">
    </div>

    <% end %>

    <p><%= link_to "Finalize Receipt", finalize_receipt_path(receipt_id: params[:receipt_id]), class: "btn btn-primary btn-important" %></p>



</section>