config/routes.rb
# TODO - change accessibility via status and user_id.
# TODO Error handling, for EVERYTHING (phone number, etc)
# TODO - get avalara to work
# TODO - tip calculator - built in to say the percentage - AJAX ?? - DO NOT WANT TO HAVE TO REFReSH.
# TODO - talk to someone about the routes - especially the AJAX routes.


Rails.application.routes.draw do
  root 'mains#index'

  get "/information/", to: "mains#information", as: "information" 

  # OmniAuth
  get "/auth/:provider/callback" => "sessions#create"

  get "/sessions/login_failure", to: "sessions#login_failure", as: "login_failure"
  get "/sessions", to: "sessions#index", as: "sessions"
  delete "/sessions", to: "sessions#destroy"

  # RECEIPT
  resources :receipts, only: [:index, :new, :show, :create, :destroy] do
    # ListItems
    resources :list_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :guests, only: [:index, :new, :create, :show, :update] do

      resources :guest_items, only: [:index]
    end
  end

  get "receipts/:receipt_id/finalize", to: "receipts#finalize", as: "finalize_receipt"

  # TO HANDLE AJAX of creating new guest
  post "receipts/:receipt_id/guests/", to: "guest_items#create_guest", as: "AJAX_create_guest"

  post "/guests/:guest_id/guest_items/", to: "guest_items#update", as: "update_guest_items"

  # Page where user can select the tip and view the total for their order
  get "guests/:guest_id/tip", to: "guests#tip", as: "guests_tip"
  post "guests/:guest_id ", to: "guests#add_tip", as: "guests_tip_add"


  # get "/receipts/guests/:id/split", to: "guests#split", as: "split_receipt"
  # post "/receipts/guests/:id/", to: "guest_items#create", as: "post_guest_items"
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  skip_before_action :require_login

  def index
    # puts RBTracer::VERSION
  end

  def information

  end 
end

app/views/mains/index.html.erb
<section>

  <h4 class="text">Welcome to <strong>RestEasy</strong>, where we split your restaurant receipt for you so you can enjoy the meal like intended </h4>


  <span class="has-tooltip" data-toggle="tooltip" title="Click to upload a photo">
    <p class="center"><%= link_to '<i class="fa fa-camera fa-5x button-icon blue-button-icon" aria-hidden="true"></i>'.html_safe, new_receipt_path, class: "btn receipt-icon button-icon center"%></p>
  </span>


  <p class="text">Begin by <strong><%= link_to "uploading your receipt", new_receipt_path%></strong>, or check out <strong><%= link_to "past receipts", receipts_path%></strong> you have split with us</p>




</section>

app/views/mains/information.html.erb
<section>

  <h2 class="logo">Welcome</h2>

  <p class="text">Welcome to RestEasy! Where we help you and your friends split your restaurant receipts. Here you will find instructions on how to optimize your experience, refer back to this page if you ever have a question about how to improve your experience. Enjoy!</p>

  <h2 class="logo">Make the most of the photos you upload</h2>

  <p class="text">Make the most of the photos you uploading. Check out some examples of photos that are best turned into text and ones that aren't. The better the photo, the less you type. To optimize phots:</p>

  <ul class="text">
    <li>Take the picture directly over the receipt</li>
    <li>Crop the receipt so only the line items are showing</li>
    <li>Optimize text clarity</li>
  </ul>



  <ul class="text">
    <h3 class="logo">Good Receipts</h3>

    <li class="no-bullet"><%=image_tag("good1.JPG", :alt => "Good Photo", :class => "receipt-image center")%>
      <p>1. Picture taken directly above receipt, 2. No letters are cut off, 3. Receipt not standing on an angle, 4. Clear text.</p>
    </li>

    <li class="no-bullet"><%=image_tag("good2.JPG", :alt => "Good Photo", :class => "receipt-image center")%>
      <p>1. Picture taken directly above receipt, 2. No letters are cut off, 3. Receipt not standing on an angle, 4. Clear text.</p>
    </li>

    <h3 class="logo">Bad Receipts</h3>

    <li class="no-bullet"><%=image_tag("angle.JPG", :alt => "Photo taken at an angle", :class => "receipt-image center")%>
      <p>Photo taken at an angle not directly over the photo.</p>
    </li>

    <li class="no-bullet"><%=image_tag("full.JPG", :alt => "Photo of full receipt", :class => "receipt-image center")%>
      <p>Photo is sideways and includes the full receipt instead of just the line items.</p>
    </li>

    <li class="no-bullet"><%=image_tag("blurry.JPG", :alt => "Blurry receipt", :class => "receipt-image center")%>
      <p>Text in receipt could be better defined.</p>
    </li>

    <li class="no-bullet"><%=image_tag("sideway.JPG", :alt => "Sideways receipt", :class => "receipt-image center")%>
      <p>Receipt is crooked and includes more text than just the line items.</p>
    </li>
    <ul>



      <ul>

        <ul>

        </section>