config/routes.rb
# TODO - change accessibility via status and user_id.
# TODO Error handling, for EVERYTHING (phone number, etc)
# TODO - get avalara to work
# TODO - tip calculator - built in to say the percentage - AJAX ?? - DO NOT WANT TO HAVE TO REFReSH.
# TODO - talk to someone about the routes - especially the AJAX routes.


Rails.application.routes.draw do
  root 'mains#index'

  get "/information/", to: "mains#information", as: "information" 

  # OmniAuth
  get "/auth/:provider/callback" => "sessions#create"

  get "/sessions/login_failure", to: "sessions#login_failure", as: "login_failure"
  get "/sessions", to: "sessions#index", as: "sessions"
  delete "/sessions", to: "sessions#destroy"

  # RECEIPT
  resources :receipts, only: [:index, :new, :show, :create, :destroy] do
    # ListItems
    resources :list_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :guests, only: [:index, :new, :create, :show, :update] do

      resources :guest_items, only: [:index]
    end
  end

  get "receipts/:receipt_id/finalize", to: "receipts#finalize", as: "finalize_receipt"

  # TO HANDLE AJAX of creating new guest
  post "receipts/:receipt_id/guests/", to: "guest_items#create_guest", as: "AJAX_create_guest"

  post "/guests/:guest_id/guest_items/", to: "guest_items#update", as: "update_guest_items"

  # Page where user can select the tip and view the total for their order
  get "guests/:guest_id/tip", to: "guests#tip", as: "guests_tip"
  post "guests/:guest_id ", to: "guests#add_tip", as: "guests_tip_add"


  # get "/receipts/guests/:id/split", to: "guests#split", as: "split_receipt"
  # post "/receipts/guests/:id/", to: "guest_items#create", as: "post_guest_items"
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :receipt
  has_many :guest_items
  #
  # def process
  #   puts ">>>>>>>> YES THE RECEipt WAS PROCESSED!!!!"
  #   puts self.id
  #
  #   # line_occurances = self.quantity
  #   # price_per_item = (self.price / self.quantity).to_f
  #   #
  #   # # To create the given number of lines (based on the quantity)
  #   # line_occurances.times do
  #   #   self.guest_items.create!(receipt_id: self.receipt_id, price: price_per_item)
  #   # end
  #
  #   # self.guest_items.create!(list_item_id: 98, price: 999.99, guest_id: 5)
  # end

end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

  def index
    if @user == nil
      redirect_to login_failure_path
    elsif @user.id != Receipt.find(params[:receipt_id]).user_id
      puts ">>>>>>>>>>>>>>" + @user.id.to_s
      redirect_to root_path, notice: "You are not logged in as the owner of this receipt"
    elsif @user.id == Receipt.find(params[:receipt_id]).user_id
      # puts ">>>>>>>>>>>>>>" + @user.id.to_s
      @receipt = Receipt.find(params[:receipt_id])

      # To display the associated list_items with the receipt instead of just the text from the receipt.
      @items_per_receipt = ListItem.where(receipt_id: @receipt.id)
    end
  end

  def edit
    # ADD CHECKING FOR USER
    @list_item = ListItem.find(params[:id])
    @quantity = :quantity
    @description = :description
    @price = :price

  end

  def update
    @this_item = ListItem.find(params[:id])
    # To identify which receipt needs to be updated
    receipt_id = ListItem.find(params[:id]).receipt_id

    if @this_item.update(list_item_params)
      puts "EDIzttttss >>>>>>>>>>>>"
      redirect_to receipt_list_items_path(receipt_id)
    else
      render :edit
    end
  end

  def new

    @new_item = ListItem.new
    @quantity = :quantity
    @description = :description
    @price = :price
  end

  def create
    @new_item = ListItem.new(list_item_params)
    if @new_item.save

      receipt_id = ListItem.find(@new_item.id).receipt_id

      @new_item.process()

      redirect_to receipt_list_items_path(receipt_id: receipt_id)
    else
      redirect_to root_path
    end
  end

  def destroy
    receipt_id = params[:receipt_id]
    @item = ListItem.find(params[:id]).destroy
    redirect_to receipt_list_items_path(receipt_id)
  end

  private

  def list_item_params
    params.require(:list_item).permit(:quantity, :description, :price, :receipt_id)
  end
end

app/views/list_items/edit.html.erb
<section>

  <h3 class="labels">Edit Entry</h3>

  </br>

  <%= form_for @list_item, :url => { method: :patch, action: :update, class: "form-horizontal" } do |f| %>

    <div class="form-group">
      <%= f.label @quantity, class: "col-md-4 control-label labels"  %>
      <%= f.text_field @quantity, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label @description, class: "col-md-4 control-label labels"  %>
      <%= f.text_field @description, class: "form-control"  %>
    </div>

    <div class="form-group">

      <%= f.label @price, class: "col-md-4 control-label labels"  %>
      <%= f.text_field @price, class: "form-control"  %>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>

  <div>
    <%= link_to "Cancel", receipt_list_items_path(receipt_id: params[:receipt_id]), class: "btn btn-primary" %>
  </div>

</section>

app/views/list_items/index.html.erb
<article>

  <section>

    <h4 class="text">Look over the receipt to confirm all details before proceeding. Once all items have been checked over, click the button at the bottom of the page to begin splitting your receipt.</h4>

  </section>

  <table class="table-responsive receipt table">
    <tr>
      <th>Quan</th>
      <th>Desc</th>
      <th>Price</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @items_per_receipt.each do |i| %>
      <tr>
        <td><%= i.quantity %></td>
        <td><%= i.description %></td>
        <td class="moneyright"><%= money_format(i.price) %></td>
        <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_receipt_list_item_path(id: i.id), class: "btn blue-button-icon"%></td>
        <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, receipt_list_item_path(id: i.id), method: :delete, class: "btn btn-danger"%></td>
      </tr>
    <% end %>

  </table>

  <div id="main-container" class="container-fluid">
    <div class="row">

      <div class="col-md-9 col-xs-12">
        <!-- TODO consider making this a modal -->
        <p><%= link_to "++ Add Missing Item", new_receipt_list_item_path(receipt_id: params[:receipt_id]), class: "btn btn-primary" %></p>
      </div>

      <div class="col-md-3 col-xs-12">
        <p><%= link_to "Let's Begin Splitting", receipt_guest_guest_items_path(receipt_id: params[:receipt_id], guest_id: Guest.find_by(receipt_id: params[:receipt_id]).id), class: "btn-primary btn" %></p>
      </div>

    </div>
  </div>



</article>

app/views/list_items/new.html.erb
<h3 class="labels"> Add an item to the receipt </h3>

</br>

<%= form_for @new_item, :url => { method: :post, action: :create } do |f| %>

  <div class="form-group">
    <%= f.label @quantity, class: "col-md-4 control-label labels"  %>
    <%= f.text_field @quantity, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label @description, class: "col-md-4 control-label labels"  %>
    <%= f.text_field @description, class: "form-control"  %>
  </div>

  <div class="form-group">

    <%= f.label @price, class: "col-md-4 control-label labels"  %>
    <%= f.text_field @price, class: "form-control"  %>
  </div>

  <%= f.hidden_field :receipt_id, :value => params[:receipt_id] %>

  <%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>

<div>
  <%= link_to "Cancel", receipt_list_items_path(receipt_id: params[:receipt_id]), class: "btn btn-primary" %>
</div>