config/routes.rb
# TODO - change accessibility via status and user_id.
# TODO Error handling, for EVERYTHING (phone number, etc)
# TODO - get avalara to work
# TODO - tip calculator - built in to say the percentage - AJAX ?? - DO NOT WANT TO HAVE TO REFReSH.
# TODO - talk to someone about the routes - especially the AJAX routes.


Rails.application.routes.draw do
  root 'mains#index'

  get "/information/", to: "mains#information", as: "information" 

  # OmniAuth
  get "/auth/:provider/callback" => "sessions#create"

  get "/sessions/login_failure", to: "sessions#login_failure", as: "login_failure"
  get "/sessions", to: "sessions#index", as: "sessions"
  delete "/sessions", to: "sessions#destroy"

  # RECEIPT
  resources :receipts, only: [:index, :new, :show, :create, :destroy] do
    # ListItems
    resources :list_items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :guests, only: [:index, :new, :create, :show, :update] do

      resources :guest_items, only: [:index]
    end
  end

  get "receipts/:receipt_id/finalize", to: "receipts#finalize", as: "finalize_receipt"

  # TO HANDLE AJAX of creating new guest
  post "receipts/:receipt_id/guests/", to: "guest_items#create_guest", as: "AJAX_create_guest"

  post "/guests/:guest_id/guest_items/", to: "guest_items#update", as: "update_guest_items"

  # Page where user can select the tip and view the total for their order
  get "guests/:guest_id/tip", to: "guests#tip", as: "guests_tip"
  post "guests/:guest_id ", to: "guests#add_tip", as: "guests_tip_add"


  # get "/receipts/guests/:id/split", to: "guests#split", as: "split_receipt"
  # post "/receipts/guests/:id/", to: "guest_items#create", as: "post_guest_items"
end

app/models/receipt.rb
# require 'rtesseract'

# require 'carrierwave/orm/activerecord'

class Receipt < ActiveRecord::Base
  belongs_to :user
  has_many :list_items
  has_many :guests

  validates :user, :presence => true


  # validates the presence of status, between 1(editable),2(splitable),3(completed)
  validates :status, presence: true, :numericality => {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3}

  def process
    # Add in tax
    self.tax = AvalaraApiWrapper.sales_tax(self.zip_code)
    self.save

    # Turns image into an array of text strings which.

    file = self.attachment.file.file
    image = RTesseract.new(file)

    @split = image.to_s.split("\n")
    # @split = ["hashd", "asdads", "$2.30"]

    @split.each do |line|
      # # Go through each line and in each line, check that the last thing is a float, the item directly before the float OR the first item is a single integer, and then it also contains some kind of aphabetical text" If all this is true, then it is a true line item in the receipt, all other receipt lines will be ignored.
      examine_line = line.split(" ")

      # Last element, check to see if it is a float - need to remove the "$" before checking

      if examine_line.length !=0 && examine_line.last.gsub("$", "").to_f != 0.0
        puts "NEW LINE"

        # A line item will only be made if a price is present. The price is the only thing that needs to be present to create the item. A price is always the last thing in the line. It should also always be a float. Once the "$" symbol is removed it should always be a float. It is not a float if when you attempt to make it into a float it turns to 0. Additionally, this is convienient because items that are free on the receipt, do not need to be accounted for and do not need to be selected by a guest.


        # To select the price in the line. NOTE Price is multiplied by 100 here, to save the digits, and then will be divided by 100 in the list_item view and whenever it is used on other models.
        price = examine_line.last.gsub("$", "").to_f

        # To select the quantity

        # OCR often reads 1 as I => including that case to identify the quantity. Also when the item is not a number (ie a letter), when you turn it into a number, it become 0. Since a quantity will never be 0, or else it wouldn't be on the receipt => so long as it is >0, it is a number and we can peg this as the quantity.

        if examine_line.first == "I" || examine_line.first.to_i > 0
          if examine_line.first == "I"
            quantity = 1
            examine_line.delete_at(0)
          else
            quantity = examine_line.first.to_i
            examine_line.delete_at(0)
          end
        end

        if examine_line[-2] == "I" || examine_line[-2].to_i > 0
          if examine_line[-2] == "I"
            quantity = 1
            examine_line.delete_at(-2)
          else
            quantity = examine_line[-2].to_i
            examine_line.delete_at(-2)
          end
        end

        # If the quantity is not registered, it is 1
        quantity ||= 1


        # To select the name/description of the item.
        examine_line.pop
        name = examine_line.join(" ")

        puts "quantity >>>>" + quantity.to_s
        puts "name >>>>" + name.to_s
        puts "price >>>>" + price.to_s


        self.list_items.create!({description: name, price: price, quantity: quantity})

      end
    end
  end

  # TODO - why is this method not working? Written in the controller, but ideally would be here.
  def change_to_splittable()
    puts "YOU HAVE ENTERED THE RECEIPT MODEL! and are about to make all the guest_items assocaited with this receipt"

    puts self
    puts "the id of the receipt is: " + self.id.to_s

    list_items = ListItem.where(receipt_id: self.id)

    # Going through the ListItems associated with the receipt, making guest_items with the number of quantity, and the price divided if the quantity > 1.
    list_items.each do |item|
      item.quantity.times do
        GuestItem.create!(list_item_id: item.id, price: (item.price/item.quantity))
        puts item.price
        puts item.quantity
        puts GuestItem.last.price
      end
    end

    # AND NOW, change the status since all the guestItems have been made.
    receipt = self
    receipt.status = 2
    receipt.save

    puts ">>>>>>>>>>>>>>>>receipt status" + receipt.status.to_s
  end


  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.

end

app/controllers/receipts_controller.rb
# require 'rtesseract'

class ReceiptsController < ApplicationController
# respond_to :html, :js

  def index
    if @user == nil
      redirect_to login_failure_path
    else
      @receipts = Receipt.where(user_id: @user.id)
    end
  end

  def new
    if @user == nil
      redirect_to login_failure_path
    else
      @receipt = Receipt.new
    end
  end

  def create
    # Calls user method in the application_controller
    user
    @current_user = User.find(@user.id)

    @receipt = @current_user.receipts.new(receipt_params)

    if @receipt.save

      # Once the receipt has been saved/registered then it should automatically also create all the list items associated with the receipt.
      @receipt.process()
      @receipt.tax()

      # IF THE RECEIPT WAS SAVED, create the first guest of the receipt, ie the user

      Guest.create!(name: @user.name, receipt_id: @receipt.id)
      puts "THE RECEIPT GUEST HAS BEEN CREAATED!!! HOPEFULLY"
      puts Guest.find_by(receipt_id: @receipt.id)

      redirect_to receipt_list_items_path(receipt_id: @receipt.id), notice: "The receipt has been uploaded"
    else
      render "new"
    end
  end

  def destroy
    if @user.id == nil
      flash[:error] = "You need to log in to edit this."
      redirect_to root_path
    elsif @user.id != Receipt.find(params[:id]).user_id
      flash[:error] = "This is not your receipt, you can't delete it"
      redirect_to root_path
    elsif @user.id == Receipt.find(params[:id]).user_id
      @receipt = Receipt.find(params[:id])
      @receipt.destroy
      redirect_to receipts_path
    end
  end

  def finalize


    @receipt = params[:receipt_id]
    @receipt_object = Receipt.find(@receipt)
    @guests_per_receipt = Guest.where(receipt_id: @receipt)
    @list_items = ListItem.where(receipt_id: @receipt)

    @guest_items = GuestItem.includes(:list_item).where(list_items: {receipt_id: @receipt})

    # You should only be able to access the finalize page if ALL items have been claimed by a guest. If it passes this loop, then all items have been seleceted and it can continue as normal.

    if !check_items(@guest_items)
      @receipt_object.status = 2
      @receipt_object.save
      redirect_to receipt_guest_guest_items_path(receipt_id: @receipt, guest_id: @guests_per_receipt.first.id)
    end


    # potentially make this a post action to change the status of the receipt and redisplay one of the previous pages, but changes.



    # Change receipt status to 3 so that the functionality of the receipt is further limited
    if @receipt_object.status != 3
      # Calls method to generate the guest methods and to change the status.
      @receipt_object.status = 3
      @receipt_object.save
    end



    # potentially move to the model.
    @receipt_tip = 0.0
    # Go through the list of guests associated with the receipt and add the tips together.
    @guests_per_receipt.each do |person|
      if person.tip != nil
        @receipt_tip += person.tip
      end
    end

    # Go through the list of items and sum them together to get the total and tax on the receipt.
    @total = 0
    @list_items.each do |item|
      @total += item.price
    end

    # TAX -- to be done when Avalara works

    @tax = @total * 0.095

    @final = @receipt_tip + @total + @tax
  end

private
  def receipt_params
    params.require(:receipt).permit(:name, :attachment, :zip_code, :status)
  end

  def check_items(guest_items)
    guest_items.each do |item|
      if item.guest_id == nil
        flash[:error] = "NOTICE: All items must be selected before finalizing the receipt"
        return false
      end
    end
    return true
  end
end

app/views/receipts/finalize.html.erb
<h3 class="text">Final Tally</h3>

<p class="text">Cost per Person</p>

<!-- Iterate through the guest to give their total, tip, tax, and final -->

<table class="table-responsive receipt table">
  <tr>
    <th>Name</th>
    <th class="moneyright">Total</th>
  </tr>
  <% @guests_per_receipt.each do |person| %>
    <tr>
    <% if person.item_total != nil %>
      <td><%= person.name %>:</td>
      <td class="moneyright"><%= money_format(person.item_total * 1.095 + person.tip) %></td>
    <% else %>
      <td><%= person.name %>:</td>
      <td class="moneyright"><%=money_format(0)%></td>
    <% end %>
    </tr>
  <% end %>

</table>

<p class="text">Final item total, tip, tax, and order total</p>

<table class="table-responsive receipt table">
  <tr>
    <th>Item Total:</th>
    <td class="moneyright"><%= money_format(@total)%></td>
  </tr>
  <tr>
    <th>Tax:</th>
    <td class="moneyright"><%=money_format(@tax)%></td>
  </tr>
  <tr>
    <th>Tip:</th>
    <td class="moneyright"><%= money_format(@receipt_tip)%></td>
  </tr>
  <tr>
    <th>Final</th>
    <td class="moneyright"><%= money_format(@final) %></td>
  </tr>

</table>

app/views/receipts/index.html.erb
<section>


<% if !flash[:error].blank? %>
  <div class="alert alert-info">
  <%= flash[:error] %>
  </div>
<% end %>

<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Receipt", new_receipt_path, class: "btn btn-primary" %>
<br />
<br />


<div id="main-container" class="container">
  <div class="row">
    <% @receipts.each do |receipt| %>
      <div class="receipt col-xs-12 col-sm-6 col-md-3 col">

        <span>
          <% if receipt.status == 1 %>
            <p class="receipt-text" ><%= link_to receipt.name, receipt_list_items_path(receipt.id), class: "receipt-text-link"%></p>
          <% elsif receipt.status == 2 %>
            <p class="receipt-text"><%= link_to receipt.name, receipt_guest_guest_items_path(receipt_id: receipt.id, guest_id: Guest.where(receipt_id: receipt.id).last), class: "receipt-text-link" %></p>
          <% elsif receipt.status == 3 %>
            <p class="receipt-text"><%= link_to receipt.name, finalize_receipt_path(receipt_id: receipt.id), class: "receipt-text-link" %></p>
          <% end %>

          <p class="receipt-text"><%= receipt.created_at.strftime("%m/%d/%Y") %></p>
        </span>

        <div class="receipt-buttons">
          <span class="has-tooltip" data-toggle="tooltip" title="Receipt Image">
            <%= link_to '<i class="fa fa-download" aria-hidden="true"></i>'.html_safe, receipt.attachment_url, class: "btn receipt-icon button-icon"%>
          </span>

          <span class="has-tooltip" data-toggle="tooltip" title="Delete Receipt">
          <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, receipt, method: :delete, class: "btn btn-danger button-icon", confirm: "Are you sure that you wish to delete #{receipt.name}?" %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

</section>

app/views/receipts/new.html.erb
<article>


  <h3 class="labels">Add a New Receipt</h3>

  </br>

  <% if !@receipt.errors.empty? %>
    <div class="alert alert-error">
      <ul>
        <% @receipt.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well">
    <%= form_for @receipt, html: { multipart: true, class: "form-horizontal" } do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "col-md-4 control-label labels"   %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :zip_code, class: "col-md-4 control-label labels"   %>
      <%= f.text_field :zip_code, class: "form-control" %>
    </div>

    <div class="form-group">
      <!-- Find a way to change the button -->
      <%= f.label :attachment, class: "col-md-4 control-label labels"  %>
      <%= f.file_field :attachment, class: "form-control"%>
    </div>

      <%= f.hidden_field :status, :value => 1 %>
      <%= f.submit "Save", class: "btn btn-primary"%>
    <% end %>
  </div>

  <div>
    <%= link_to "Cancel", receipts_path, class: "btn btn-primary" %>
  </div>

</article>

app/views/receipts/show.html.erb
<article>

  <section>
    <h1>You are displaying the show page for <%= @receipt.zip_code %></h1>
  </section>

  <section>
    <p><%= link_to "New List Item", new_list_item_path(receipt_id: params[:id]) %></p>
    <p><%= params[:id] %></p>

  </section>

  <table>
    <tr>
      <th>Quantity</th>
      <th>Description</th>
      <th>Price</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @items_per_receipt.each do |i| %>
      <tr>
        <td><%= i.quantity %></td>
        <td><%= i.description %></td>
        <td><%= "%.2f" % i.price %></td>
        <td><%= link_to "Edit", edit_list_item_path(i.id) %></td>
      </tr>
    <% end %>
  </table>

</article>